name: MR_POLICEMAN CI/CD

on:
    push:
        branches:
        - main
    paths:
      - 'src/server/**'
      - '.github/workflows/main.yml'
    pull_request:
        branches:
        - main

env:
  PORT: ${{ secrets.PORT }}
  POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
  SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  GOOGLE_CALLBACK_URL: ${{ secrets.GOOGLE_CALLBACK_URL }}
  CLIENT_URL: ${{ secrets.CLIENT_URL }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  RADAR_API_ENDPOINT: ${{ secrets.RADAR_API_ENDPOINT }}

  jobs:
    test:
      runs-on: ubuntu-latest

      steps:
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 20.x

        - name: Install Dependencies
        - run: npm install

        - name: Run Unit Tests
        - run: npx vitest